//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_quanao.Admin {
    
    
    public partial class Sizes {
        
        /// <summary>
        /// ucSize_add control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shop_quanao.Admin.UserControls.Size_add ucSize_add;
        
        /// <summary>
        /// ucSize_list control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shop_quanao.Admin.UserControls.Size_list ucSize_list;
        
        /// <summary>
        /// ucSize_update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shop_quanao.Admin.UserControls.Size_update ucSize_update;
    }
}
