//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_quanao.Admin {
    
    
    public partial class users {
        
        /// <summary>
        /// ucuser_add control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shop_quanao.Admin.UserControls.user_add ucuser_add;
        
        /// <summary>
        /// ucuser_list control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shop_quanao.Admin.UserControls.user_list ucuser_list;
        
        /// <summary>
        /// ucuser_update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::shop_quanao.Admin.UserControls.user_update ucuser_update;
    }
}
